export const Edges = [
  { id: "e1-2", source: "1", target: "2" },
  { id: "e2-3", source: "2", target: "3" },
  { id: "e2-4", source: "2", sourceHandle: "right-source", target: "4", type: "bezier",  style: { stroke: "blue" } },
  { id: "e2-5", source: "2", sourceHandle: "right-source", target: "5", type: "bezier",  style: { stroke: "blue" } },
  { id: "e2-6", source: "2", sourceHandle: "right-source", target: "6", type: "bezier",  style: { stroke: "blue" } },
  { id: "e2-7", source: "2", sourceHandle: "right-source", target: "7", type: "bezier",  style: { stroke: "blue" } },
  { id: "e2-8", source: "2", sourceHandle: "right-source", target: "8", type: "bezier",  style: { stroke: "blue" } },
  { id: "e2-9", source: "2", sourceHandle: "right-source", target: "9", type: "bezier",  style: { stroke: "blue" } },
  { id: "e11-12",source:"11", target:"12"},
  { id: "e12-14",source:"12",target:"14"},
  { id: "e13-15",source:"13",sourceHandle: "left-source", target:"15",targetHandle: "right-target"}, 
  { id: "e18-13",source:"18",sourceHandle: "left-source",target:"13",targetHandle: "left-target"},
  { id: "e18-23",source:"18",sourceHandle: "bottom-source", target:"23",targetHandle: "top-target"},
  { id: "e18-21",source:"18",sourceHandle: "top-source",target:"21",targetHandle: "bottom-target",type:"step"},
  { id: "e18-22",source:"18",sourceHandle: "top-source",target:"22",targetHandle: "bottom-target",type:"step"},
  { id:"e23-24",source:"23",target:"24"},
  { id:"e23-25",source:"23",sourceHandle: "bottom-source",target:"25", targetHandle: "top-target"},
  { id:"e24-26",source:"24",target:"26"},
  { id:"e26-27",source:"26",target:"27", sourceHandle: "left-source"},
  { id:"e26-28",source:"26",target:"28", sourceHandle: "left-source"},
  { id:"e26-29",source:"26",target:"29", sourceHandle: "left-source"},
  { id:"e26-30",source:"26",target:"30", sourceHandle: "left-source"},
  { id:"e26-31",source:"26",target:"31", sourceHandle: "left-source"},
  { id:"e26-32",source:"26",target:"32", sourceHandle: "right-source"},
  { id:"e32-33",source:"32",target:"33", sourceHandle: "right-source"},
  { id:"e32-34",source:"32",target:"34", sourceHandle: "right-source"},
  { id:"e32-35",source:"32",target:"35", sourceHandle: "right-source"},
  { id:"e36-32",source:"36",sourceHandle: "top-source",target:"32",targetHandle: "bottom-target"},
  { id:"e37-36",source:"37",sourceHandle: "left-source",target:"36",targetHandle:"right-target"},
  { id:"e37-38",source:"37",target:"38", sourceHandle: "left-source",type:"step"},
  { id:"e37-39",source:"37",target:"39", sourceHandle: "left-source",type:"step"},
  { id:"e37-40",source:"37",target:"40", sourceHandle: "left-source",type:"step"},
  { id:"e37-41",source:"37",target:"41", sourceHandle: "left-source",type:"step"},
  { id:"e37-42",source:"37",target:"42"},
  { id:"e50-43",source:"50",target:"43",sourceHandle: "left-source"},
  { id:"e50-51",source:"50",target:"51",sourceHandle: "right-source"},
  { id:"e36-44",source:"36",target:"44",type:"step"},
  { id:"e67-77",source:"67",target:"77",sourceHandle: "bottom-source"},
  { id:"e51-52",source:"51",target:"52",type:"step"},
  { id:"e68-67",source:"68",sourceHandle:"right-source",target:"67",targetHandle:"left-target"},
  { id:"e67-56",source:"67",target:"56"},
  { id:"e70-71",source:"70",target:"71",type:"step"},
  { id:"e70-72",source:"70",target:"72",type:"step"},
  { id:"e70-83",source:"70",target:"83",type:"step"},
  { id:"e68-69",source:"68",sourceHandle:"left-source",target:"69"},
  { id:"e69-70",source:"69",target:"70",sourceHandle: "right-source",targetHandle: "left-target"},
  { id:"e82-68",source:"82",target:"68"},
  { id:"e83-84",source:"83",target:"84",sourceHandle: "right-source", type: "bezier",style: { stroke: "blue" }},
  { id:"e83-85",source:"83",target:"85",sourceHandle: "right-source", type: "bezier",style: { stroke: "blue" }},
  { id:"e83-86",source:"83",target:"86",sourceHandle: "right-source", type: "bezier",style: { stroke: "blue" }},
  { id:"e83-87",source:"83",target:"87",sourceHandle: "right-source", type: "bezier",style: { stroke: "blue" }},
  { id:"e83-88",source:"83",target:"88",sourceHandle: "right-source", type: "bezier",style: { stroke: "blue" }},
  { id:"e83-90",source:"83",target:"90"},
  { id:"e89-95",source:"89",target:"95"},
  { id:"e89-90",source:"89",target:"90",sourceHandle: "top-source"},
  { id:"e89-91",source:"89",target:"91",sourceHandle: "right-source"},
  { id:"e91-93",source:"91",target:"93"},
  { id:"e91-94",source:"91",sourceHandle:"right-source",target:"94",targetHandle:"left-target"},
  { id:"e98-99",source:"98",target:"99",sourceHandle: "left-source"},
  { id:"e98-100",source:"98",target:"100",sourceHandle: "left-source"},
  { id:"e98-101",source:"98",target:"101",sourceHandle: "left-source"},
  { id:"e98-94",source:"98",sourceHandle: "top-source",target:"94",targetHandle:"bottom-target"},
  { id:"e98-105",source:"98",target:"105",sourceHandle: "bottom-source",type:"step"},
  { id:"e105-104",source:"105",target:"104"},

];

