 
 export const Nodes = [
  { id: "1", position: { x: 0, y: 0 }, data: { label: "Front-end" }, style: { background: "white", border: "none" } },
  { id: "2", position: { x: 0, y: 100 }, data: { label: "Internet" }, type: "twoSourceOneTarget", style: { background: "yellow" } },
  { id: "3", position: { x: 0, y: 200 }, data: { label: "HTML" },targetPosition: "top", style: { background: "yellow" } },
  { id: "4", position: { x: 350, y: -50 }, data: { label: "How does the internet work?" },targetPosition:"left", style: { background: "#FFE599" ,Maxwidth:"30%"} },
  { id: "5", position: { x: 350, y: 20 },  data: { label: "What is HTTP?" },targetPosition:"left", style: { background: "#FFE599" } },
  { id: "6", position: { x: 350, y: 90 },  data: { label: "What is Domain Name?" },targetPosition:"left", style: { background: "#FFE599" } },
  { id: "7", position: { x: 350, y: 160 }, data: { label: "What is hosting?" },targetPosition:"left", style: { background: "#FFE599" } },
  { id: "8", position: { x: 350, y: 230 }, data: { label: "DNS and how it works?" },targetPosition:"left", style: { background: "#FFE599" } },
  { id: "9", position: { x: 350, y: 300 }, data: { label: "Browsers and how they work?" },targetPosition:"left", style: { background: "#FFE599" } },
  { id:"10", position: { x: 0, y:250}, data:{label:"CSS"},style: { background: "yellow" }},
  { id:"11", position: { x: 0, y:300}, data:{label:"Java Script"},style: { background: "yellow" }},
  { id:"12", position: { x: 0, y:490}, data:{label:"Version control"}, sourcePosition:"left",style: { background: "yellow" }},
  { id:"13", position: { x: 0, y:550}, data:{label:"VCS Hosting"},targetPosition:"right",style: { background: "yellow" }},
  { id:"14", position: { x:-210,y:490},data:{label:"Git"},targetPosition:"right",style: { background: "#ffe699d8" }},
  { id:"15", position: { x:-210,y:550},data:{label:"GitHub"},targetPosition:"right",style: { background: "#ffe699d8" }},
  { id:"16", position: { x:-380,y:550},data:{label:"GitLab"},style: { background: "#ffe699d8" }},
  { id:"17", position: { x:-400,y:200},data:{label:"HTML,CSS and JavaScript are the backbone of web development Make sure to practice by building lots of projects"},type: "custom"},
  { id:"18", position: { x:350, y:550},data:{label:"Pakage Managers"},type:"twoSourceOneTarget",style: { background: "yellow" }},
  { id:"19", position: { x:250, y:410},data:{label:"pnpm"},style: { background: "#ffe699d8" }},
  { id:"20", position: { x:430, y:410},data:{label:"Bun"},style: { background: "#ffe699d8" }},
  { id:"21", position: { x:250, y:460},data:{label:"npm"},targetPosition:"bottom",style: { background: "#ffe699d8" }},
  { id:"22", position: { x:430, y:460},data:{label:"Yarn"},targetPosition:"bottom",style: { background: "#ffe699d8" }},
  { id:"23", position: { x:350, y:640},data:{label:"CSS Framework"},type: "twoSourceOneTarget",style: { background: "yellow"}},
  { id:"24", position: { x:-30,y:620},data:{label:"At this point you should be able to build modern vanila Js Frontend application"},type: "custom",targetPosition:"bottom"},
  { id:"25", position: { x:350, y:710},data:{label:"Tailwind"},targetPosition:"top",style: { background: "#ffe699d8" }},
  { id:"26", position: { x:0,y:860},data:{label:"Learn a FrameWork"},sourcePosition:"left",style: { background: "yellow" }},
  { id:"27", position: { x:-250, y:860},data:{label:"solid"},  targetPosition:"right", style: { background: "#ffe699d8" }},
  { id:"28", position: { x:-250, y:820},data:{label:"Svelte"}, targetPosition:"right", style: { background: "#ffe699d8" }},
  { id:"29", position: { x:-250, y:780},data:{label:"Angular"},targetPosition:"right", style: { background: "#ffe699d8" }},
  { id:"30", position: { x:-250, y:740},data:{label:"Vue.js"}, targetPosition:"right", style: { background: "#ffe699d8" }},
  { id:"31", position: { x:-250, y:700},data:{label:"React"},  targetPosition:"right", style: { background: "#ffe699d8" }},
  { id:"32", position: { x:250, y:860}, data:{label:"Linters & Formatters"},type: "twoSourceOneTarget",style: { background: "yellow" }},
  { id:"33", position: { x:450, y:860}, data:{label:"Biome"},  targetPosition:"left",style: { background: "#ffe699d8" }},
  { id:"34", position: { x:450, y:900}, data:{label:"Prettier"},targetPosition:"left", style: { background: "#ffe699d8" }},
  { id:"35", position: { x:450, y:940}, data:{label:"ESLint"},targetPosition:"left", style: { background: "#ffe699d8" }},
  { id:"36", position: { x:250, y:1000},data:{label:"Module Bundlers"},targetPosition:"left",style:{ background: "yellow" }},
  { id:"37", position: { x:0, y:1000},data:{label:"Testing"},type: "twoSourceOneTarget",style:{ background: "yellow" }},
  { id:"38", position: { x:-250,y:1000},data:{label:"Vitest"},targetPosition:"right",style: { background: "#ffe699d8" }},
  { id:"39", position: { x:-250,y:1040},data:{label:"Jest"},targetPosition:"right",style: { background: "#ffe699d8" }},
  { id:"40", position: { x:-250,y:1080},data:{label:"Playwright"},targetPosition:"right",style: { background: "#ffe699d8" }},
  { id:"41", position: { x:-250,y:1120},data:{label:"cypress"},targetPosition:"right",style: { background: "#ffe699d8" }},
  { id:"42", position: { x:0,y:1080},data:{label:"Auth strategies"},style:{ background: "yellow" }},
  { id:"43", position: { x:-80,y:1190},data:{label:"At this point you should have the expertise od an intermediate level frontend developer.keep practicing and sharpening your skills"},targetPosition:"right",type: "custom"},
  { id:"44", position: { x:340,y:1070},data:{label:"Vite"},style: { background: "#ffe699d8" }},
  { id:"45", position: { x:250,y:1120},data:{label:"SWC"},style: { background: "#ffe699d8" }},
  { id:"46", position: { x:420,y:1120},data:{label:"esbuild"},style: { background: "#ffe699d8" }},
  { id:"47", position: { x:250,y:1160},data:{label:"Roolup"},style: { background: "#ffe699d8" }},
  { id:"48", position: { x:420,y:1160},data:{label:"Rolldown"},style: { background: "#ffe699d8" }},
  { id:"49", position: { x:340,y:1210},data:{label:"Parcel"},style: { background: "#ffe699d8" }},
  { id:"50", position: { x:240,y:1270},data:{label:"Web APIs"},type:"twoSourceOneTarget",style: { background: "yellow" }},
  { id:"51", position: { x:410,y:1270},data:{label:"Web Security"},targetPosition:"left",style: { background: "yellow" }},
  { id:"52", position: { x:510,y:1340},data:{label:"OWASP Risks"},style: { background: "#ffe699d8" }},
  { id:"53", position: { x:510,y:1380},data:{label:"CSP"},style: { background: "#ffe699d8" }},
  { id:"54", position: { x:510,y:1420},data:{label:"HTTPS"},style: { background: "#ffe699d8" }},
  { id:"55", position: { x:510,y:1460},data:{label:"CORS"},style: { background: "#ffe699d8" }},
  { id:"56", position: { x:410,y:1560},data:{label:"SSR"},targetPosition:"bottom",style: { background: "Yellow"}},
  { id:"57", position: { x:10,y:1510},data:{label:"Angular"},style: { background: "#ffe699d8" }},
  { id:"58", position: { x:10,y:1560},data:{label:"Vue.js"},style: { background: "#ffe699d8" }},
  { id:"59", position: { x:10,y:1610},data:{label:"Nux.js"},style: { background: "#ffe699d8" }},
  { id:"60", position: { x:10,y:1660},data:{label:"svelte Kit"},style: { background: "#ffe699d8" }},
  { id:"61", position: { x:10,y:1710},data:{label:"Svelte"},style: { background: "#ffe699d8" }},
  { id:"62", position: { x:180,y:1510},data:{label:"React"},style: { background: "#ffe699d8" }},
  { id:"63", position: { x:180,y:1560},data:{label:"Next.js"},style: { background: "#ffe699d8" }},
  { id:"64", position: { x:180,y:1610},data:{label:"Tanstack start"},style: { background: "#ffe699d8" }},
  { id:"65", position: { x:180,y:1660},data:{label:"Astro"},style: { background: "#ffe699d8" }},
  { id:"66", position: { x:180,y:1710},data:{label:"react-router"},style: { background: "#ffe699d8" }},
  { id:"67", position: { x:410,y:1770},data:{label:"SSG"}, type: "twoSourceOneTarget",style: { background: "yellow" }},
  { id:"68", position: { x:180,y:1770},data:{label:"type checkers"},targetPosition:"right",style: { background: "yellow" }},
  { id:"69", position: { x:10,y:1770},data:{label:"Design systems"},style: { background: "Yellow" }},
  { id:"70", position: { x:-320,y:1770},data:{label:"deployment"},sourcePosition:"top",style: { background: "yellow" }},
  { id:"71", position: { x:-230,y:1680},data:{label:"Render"},targetPosition:"bottom",style: { background: "#ffe699d8" }},
  { id:"72", position: { x:-390,y:1680},data:{label:"Railway"},targetPosition:"bottom",style: { background: "#ffe699d8" }},
  { id:"73", position: { x:-320,y:1635},data:{label:"CloudFlare"},style: { background: "#ffe699d8" }},
  { id:"74", position: { x:-390,y:1590},data:{label:"Vercel"},style: { background: "#ffe699d8" }},
  { id:"75", position: { x:-230,y:1590},data:{label:"Netlify"},style: { background: "#ffe699d8" }},
  { id:"76", position: { x:-320,y:1540},data:{label:"GitHub Pages"},style: { background: "#ffe699d8" }},
  { id:"77", position: { x:410,y:1840},data:{label:"Astro"},style: { background: "#ffe699d8" }},
  { id:"78", position: { x:410,y:1890},data:{label:"Next.js"},style: { background: "#ffe699d8" }},
  { id:"79", position: { x:410,y:1940},data:{label:"VuePress"},style: { background: "#ffe699d8" }},
  { id:"80", position: { x:410,y:1990},data:{label:"Eleventy"},style: { background: "#ffe699d8" }},
  { id:"81", position: { x:410,y:2040},data:{label:"Nuxt.js"},style: { background: "#ffe699d8" }},
  { id:"82", position: { x:180,y:1840},data:{label:"TypeScript"},style: { background: "#4fc2f8d8" }},
  { id:"83", position: { x:-320,y:1920},data:{label:"Performance"},type: "twoSourceOneTarget",style: { background: "yellow" }},
  { id:"84", position: { x:-120,y:1840},data:{label:"lighthouse"},targetPosition:"left",style: { background: "#ffe699d8" }},
  { id:"85", position: { x:-120,y:1890},data:{label:"DevTools Usage"},targetPosition:"left",style: { background: "#ffe699d8" }},
  { id:"86", position: { x:-120,y:1940},data:{label:"Service Workers"},targetPosition:"left",style: { background: "#ffe699d8" }},
  { id:"87", position: { x:-120,y:1990},data:{label:"Cache-control"},targetPosition:"left",style: { background: "#ffe699d8" }},
  { id:"88", position: { x:-120,y:2040},data:{label:"Streamed Responses"},targetPosition:"left",style: { background: "#ffe699d8" }},
  { id:"89", position: { x:-320,y:2090},data:{label:"Web components"},type: "twoSourceOneTarget",style: { background: "yellow" }},
  { id:"90", position: { x:-320,y:2010},data:{label:"Accessibility"},targetPosition:"top",style: { background: "yellow" }},
  { id:"91", position: { x:180,y:2090},data:{label:"GraphQL"},targetPosition:"left",style: { background: "yellow"}},
  { id:"92", position: { x:180,y:1990},data:{label:"Relay Modern"},style: { background: "#ffe699d8" }},
  { id:"93", position: { x:180,y:2040},data:{label:"Apollo"},style: { background: "#ffe699d8" }},
  { id:"94", position: { x:410,y:2090},data:{label:"PWAs"},targetPosition:"bottom",sourcePosition:"left",style: { background: "Yellow" }},
  { id:"95", position: { x:-320,y:2160},data:{label:"HTML Templates"},targetPosition:"top",style: { background: "#ffe699d8" }},
  { id:"96", position: { x:-320,y:2210},data:{label:"Custom Elemnts"},style: { background: "#ffe699d8" }},
  { id:"97", position: { x:-320,y:2260},data:{label:"Shadow DOM"},style: { background: "#ffe699d8" }},
  { id:"98", position: { x:410,y:2210},data:{label:"Mobile Apps"},type: "twoSourceOneTarget",style: { background: "yellow" }},
  { id:"99",position: { x:180,y:2180},data:{label:"React Native"},targetPosition:"right",style: { background: "#ffe699d8" }},
  { id:"100",position: { x:180,y:2230},data:{label:"Flutter"},targetPosition:"right",style: { background: "#ffe699d8" }},
  { id:"101",position: { x:180,y:2280},data:{label:"Ionic"},targetPosition:"right",style: { background: "#ffe699d8" }},
  { id:"102",position: { x:-50,y:2180},data:{label:"Electron"},style: { background: "#ffe699d8" }},
  { id:"103",position: { x:-50,y:2230},data:{label:"Tauri"},style: { background: "#ffe699d8" }},
  { id:"104",position: { x:-50,y:2280},data:{label:"Flutter"},targetPosition:"bottom",style: { background: "#ffe699d8" }},
  { id:"105",position: { x:-50,y:2360},data:{label:"Desktop Apps"},targetPosition:"right",style: { background: "yellow" }},
];